services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data2
  fulltechapidesafio:
    image: fulltechapidesafio
    build:
      context: .
      dockerfile: Dockerfile
